<div class="main-content">
   <div class="main">
      <nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
         <div class="ancient_left">
            <div class="brand_icons">
               <img src="<?php echo $this->getViewFileUrl('svg/Ancient_Icon.svg'); ?>" alt="">
            </div>
            <h3>ANCIENT</h3>
            <a href="#">Panchabhoothas</a>
            <a href="#" >What is yoga</a>
            <a href="#" >Seven chakra</a>
            <a href="#" >Meditation in ancient cultures all over the world</a>
            <div class="arrow_1" id="showLeftPush_2">
               <i  class="fa fa-arrow-right" aria-hidden="true"></i>
               <i class="fa fa-times" aria-hidden="true"></i>
            </div>
         </div>
      </nav>
      <nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right" id="cbp-spmenu-s2">
         <div class="science_right">
            <div class="brand_icons">
               <img src="<?php echo $this->getViewFileUrl('svg/Science_Icon.svg'); ?>" alt="">
            </div>
            <h3>SCIENCE</h3>
            <a href="#">Benefits of yoga & Benefits of meditation</a>
            <a href="#" >Life force energy</a>
            <a href="#">Aroma therapy</a>
            <a href="#">Colour therapy</a>
            <!-- <a href="#">Sound therapy</a> -->
            <a href="#">Magnet therapy</a>
            <a href="#">Mudras</a>
            <div class="arrow_2" id="showRightPush_2" >
               <i class="fa fa-arrow-left"  aria-hidden="true"></i>
               <i class="fa fa-times" aria-hidden="true"></i>
            </div>
         </div>
      </nav>
      <div class="yogi">
         <img src="<?php echo $this->getViewFileUrl('svg/yogi.svg'); ?>"  alt="Not-Found" />
      </div>
      <div class="banner-slider-content">
         <div id="owlslider" class="owl-carousel owl-theme">
            <div class="item">
               <p>Welcome to the space where you can better your life in easier way</p>
            </div>
            <div class="item">
               <p>Esy new life is trying to help all range of human beings over the world who differs from age to age, culture place, percepetion.</p>
            </div>
            <div class="item">
               <p>This website is to show light on your unseen inside.</p>
            </div>
         </div>
      </div>
      <div class="banner-side-menu">
         <div class="container">
            <div class="ancient">
               <img src="<?php echo $this->getViewFileUrl('svg/Ancient_Icon.svg') ?>" alt="" class="banner-side-image">
               <h3 class="banner-side-text">ANCIENT</h3>
               <div class="arrow" id="showLeftPush">
                  <i  class="fa fa-arrow-left" aria-hidden="true"></i>
               </div>
            </div>
            <div class="science">
               <img src="<?php echo $this->getViewFileUrl('svg/Science_Icon.svg') ?>" alt="" class="banner-side-image">
               <h3 class="banner-side-text" >SCIENCE</h3>
               <div class="arrow_3" id="showRightPush">
                  <i  class="fa fa-arrow-right" aria-hidden="true"></i>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>