<div class="main-content">

      <div class="yogi">
         <img src="<?php echo $this->getViewFileUrl('svg/yogi.svg'); ?>"  alt="Not-Found" />
      </div>
      <div class="banner-slider-content">
         <div id="owlslider" class="owl-carousel owl-theme">
            <div class="item">
               <p>Welcome to the space where you can better your life in easier way</p>
            </div>
            <div class="item">
               <p>Esy new life is trying to help all range of human beings over the world who differs from age to age, culture place, percepetion.</p>
            </div>
            <div class="item">
               <p>This website is to show light on your unseen inside.</p>
            </div>
         </div>
      </div>
      <div class="banner-side-menu navigation-side-menu">
            <div class="ancient">
               <img src="<?php echo $this->getViewFileUrl('svg/Ancient_Icon.svg') ?>" alt="" class="banner-side-image">
               <h3 class="banner-side-text">ANCIENT</h3>
            </div>
            <div class="science">
               <img src="<?php echo $this->getViewFileUrl('svg/Science_Icon.svg') ?>" alt="" class="banner-side-image">
               <h3 class="banner-side-text" >SCIENCE</h3>
            </div>
      </div>
</div>


<div class="post">
        <div class="container">
            
    <h1>Latest Post</h1>

    <div class="row">
        <div class="col-sm-4">
            <div class="post-1 post_hover">
                   <a href="Meditation.html"><img class="image" src="<?php echo $this->getViewFileUrl('images/img-right3-home2.png') ?>" alt="" />
                   <div class="post_middle">
                    <div class="text">Meditation</div>
                  </div> </a>
            </div>
        </div>
        <div class="col-sm-4">
                <div class="post-2 post_hover">
                       <a href="chakra.html"><img class="image" src="<?php echo $this->getViewFileUrl('images/7-Chakras-of-Human-Body.jpg') ?>" alt="">
                       <div class="post_middle">
                        <div class="text">Seven chakra</div>
                      </div> </a>
                    </div>
        </div>
        <div class="col-sm-4">
                <div class="post-3 post_hover">
                       <a href="panchabhoothas.html"><img class="image" src="<?php echo $this->getViewFileUrl('images/panchabhoothas.jpg') ?>" alt="">
                       <div class="post_middle">
                        <div class="text">panchabhoothas</div>
                      </div> </a>
                    </div>
        </div>
    </div>
        </div>

</div>

<div class="gate-way">
    <h1>Gateway</h1>
<div class="gate-way-btn">
<a href="gateway.html"><input type="button" value="Learn more"></a> </div>
</div>